# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDUyYWVkNDc1OWEyZGJiZmY5YTIzNzRhNTE0ODRjNWU2YjU0MjJhOTYxMDRlZWVlYWVhMWIyMzM1YmQxMGM3N2MwYzkyZjkxODlkZjhmMTM2MThiODgzYTNiZWFjZDlmNGI4MGJhOWNiNzFmNmFhM2EwYWRjMDU5MzdjMDM5MTk=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: coopfull
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: coopfull
    password:
