export enum LivestockProductionMode {
  FAMILY = 'FAMILY',

  INDIVIDUAL = 'INDIVIDUAL',

  COMMERCIAL = 'COMMERCIAL',

  COOPERATIVE = 'COOPERATIVE',

  CONTRACTUAL = 'CONTRACTUAL',

  OTHER = 'OTHER',
}
