package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AgriculturalProductionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalProductionAllPropertiesEquals(AgriculturalProduction expected, AgriculturalProduction actual) {
        assertAgriculturalProductionAutoGeneratedPropertiesEquals(expected, actual);
        assertAgriculturalProductionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalProductionAllUpdatablePropertiesEquals(
        AgriculturalProduction expected,
        AgriculturalProduction actual
    ) {
        assertAgriculturalProductionUpdatableFieldsEquals(expected, actual);
        assertAgriculturalProductionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalProductionAutoGeneratedPropertiesEquals(
        AgriculturalProduction expected,
        AgriculturalProduction actual
    ) {
        assertThat(actual)
            .as("Verify AgriculturalProduction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalProductionUpdatableFieldsEquals(AgriculturalProduction expected, AgriculturalProduction actual) {
        assertThat(actual)
            .as("Verify AgriculturalProduction relevant properties")
            .satisfies(a -> assertThat(a.getArea()).as("check area").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getArea()))
            .satisfies(a -> assertThat(a.getAreaUnit()).as("check areaUnit").isEqualTo(expected.getAreaUnit()))
            .satisfies(a -> assertThat(a.getPlantingDate()).as("check plantingDate").isEqualTo(expected.getPlantingDate()))
            .satisfies(a -> assertThat(a.getHarvestStartDate()).as("check harvestStartDate").isEqualTo(expected.getHarvestStartDate()))
            .satisfies(a -> assertThat(a.getHarvestEndDate()).as("check harvestEndDate").isEqualTo(expected.getHarvestEndDate()))
            .satisfies(a ->
                assertThat(a.getProductionQuantity())
                    .as("check productionQuantity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getProductionQuantity())
            )
            .satisfies(a -> assertThat(a.getProductionUnit()).as("check productionUnit").isEqualTo(expected.getProductionUnit()))
            .satisfies(a ->
                assertThat(a.getExpectedAnnualProduction())
                    .as("check expectedAnnualProduction")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExpectedAnnualProduction())
            )
            .satisfies(a -> assertThat(a.getNumberOfPlants()).as("check numberOfPlants").isEqualTo(expected.getNumberOfPlants()))
            .satisfies(a ->
                assertThat(a.getPlantingDensity())
                    .as("check plantingDensity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPlantingDensity())
            )
            .satisfies(a -> assertThat(a.getProductionYear()).as("check productionYear").isEqualTo(expected.getProductionYear()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalProductionUpdatableRelationshipsEquals(
        AgriculturalProduction expected,
        AgriculturalProduction actual
    ) {
        assertThat(actual)
            .as("Verify AgriculturalProduction relationships")
            .satisfies(a ->
                assertThat(a.getAgriculturalActivity()).as("check agriculturalActivity").isEqualTo(expected.getAgriculturalActivity())
            )
            .satisfies(a -> assertThat(a.getCrop()).as("check crop").isEqualTo(expected.getCrop()))
            .satisfies(a -> assertThat(a.getCropVariety()).as("check cropVariety").isEqualTo(expected.getCropVariety()));
    }
}
