package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AgriculturalActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalActivityAllPropertiesEquals(AgriculturalActivity expected, AgriculturalActivity actual) {
        assertAgriculturalActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertAgriculturalActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalActivityAllUpdatablePropertiesEquals(AgriculturalActivity expected, AgriculturalActivity actual) {
        assertAgriculturalActivityUpdatableFieldsEquals(expected, actual);
        assertAgriculturalActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalActivityAutoGeneratedPropertiesEquals(AgriculturalActivity expected, AgriculturalActivity actual) {
        assertThat(actual)
            .as("Verify AgriculturalActivity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalActivityUpdatableFieldsEquals(AgriculturalActivity expected, AgriculturalActivity actual) {
        assertThat(actual)
            .as("Verify AgriculturalActivity relevant properties")
            .satisfies(a ->
                assertThat(a.getTotalArea()).as("check totalArea").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalArea())
            )
            .satisfies(a -> assertThat(a.getAreaUnit()).as("check areaUnit").isEqualTo(expected.getAreaUnit()))
            .satisfies(a -> assertThat(a.getExploitationMode()).as("check exploitationMode").isEqualTo(expected.getExploitationMode()))
            .satisfies(a -> assertThat(a.getOwnershipType()).as("check ownershipType").isEqualTo(expected.getOwnershipType()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a ->
                assertThat(a.getIrrigationAvailable()).as("check irrigationAvailable").isEqualTo(expected.getIrrigationAvailable())
            )
            .satisfies(a -> assertThat(a.getOrganicProduction()).as("check organicProduction").isEqualTo(expected.getOrganicProduction()))
            .satisfies(a -> assertThat(a.getCertification()).as("check certification").isEqualTo(expected.getCertification()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgriculturalActivityUpdatableRelationshipsEquals(AgriculturalActivity expected, AgriculturalActivity actual) {
        assertThat(actual)
            .as("Verify AgriculturalActivity relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
