package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AquaticSpeciesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquaticSpeciesAllPropertiesEquals(AquaticSpecies expected, AquaticSpecies actual) {
        assertAquaticSpeciesAutoGeneratedPropertiesEquals(expected, actual);
        assertAquaticSpeciesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquaticSpeciesAllUpdatablePropertiesEquals(AquaticSpecies expected, AquaticSpecies actual) {
        assertAquaticSpeciesUpdatableFieldsEquals(expected, actual);
        assertAquaticSpeciesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquaticSpeciesAutoGeneratedPropertiesEquals(AquaticSpecies expected, AquaticSpecies actual) {
        assertThat(actual)
            .as("Verify AquaticSpecies auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquaticSpeciesUpdatableFieldsEquals(AquaticSpecies expected, AquaticSpecies actual) {
        assertThat(actual)
            .as("Verify AquaticSpecies relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getScientificName()).as("check scientificName").isEqualTo(expected.getScientificName()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getFreshwater()).as("check freshwater").isEqualTo(expected.getFreshwater()))
            .satisfies(a -> assertThat(a.getSaltwater()).as("check saltwater").isEqualTo(expected.getSaltwater()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquaticSpeciesUpdatableRelationshipsEquals(AquaticSpecies expected, AquaticSpecies actual) {
        // empty method
    }
}
