package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AquacultureProductionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquacultureProductionAllPropertiesEquals(AquacultureProduction expected, AquacultureProduction actual) {
        assertAquacultureProductionAutoGeneratedPropertiesEquals(expected, actual);
        assertAquacultureProductionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquacultureProductionAllUpdatablePropertiesEquals(
        AquacultureProduction expected,
        AquacultureProduction actual
    ) {
        assertAquacultureProductionUpdatableFieldsEquals(expected, actual);
        assertAquacultureProductionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquacultureProductionAutoGeneratedPropertiesEquals(
        AquacultureProduction expected,
        AquacultureProduction actual
    ) {
        assertThat(actual)
            .as("Verify AquacultureProduction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquacultureProductionUpdatableFieldsEquals(AquacultureProduction expected, AquacultureProduction actual) {
        assertThat(actual)
            .as("Verify AquacultureProduction relevant properties")
            .satisfies(a -> assertThat(a.getProductionDate()).as("check productionDate").isEqualTo(expected.getProductionDate()))
            .satisfies(a -> assertThat(a.getNumberOfAnimals()).as("check numberOfAnimals").isEqualTo(expected.getNumberOfAnimals()))
            .satisfies(a ->
                assertThat(a.getStockingDensity())
                    .as("check stockingDensity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getStockingDensity())
            )
            .satisfies(a ->
                assertThat(a.getProductionQuantity())
                    .as("check productionQuantity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getProductionQuantity())
            )
            .satisfies(a -> assertThat(a.getProductionUnit()).as("check productionUnit").isEqualTo(expected.getProductionUnit()))
            .satisfies(a ->
                assertThat(a.getAverageWeightGrams())
                    .as("check averageWeightGrams")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAverageWeightGrams())
            )
            .satisfies(a -> assertThat(a.getMortalityCount()).as("check mortalityCount").isEqualTo(expected.getMortalityCount()))
            .satisfies(a -> assertThat(a.getStockingCount()).as("check stockingCount").isEqualTo(expected.getStockingCount()))
            .satisfies(a -> assertThat(a.getHarvestedCount()).as("check harvestedCount").isEqualTo(expected.getHarvestedCount()))
            .satisfies(a ->
                assertThat(a.getExpectedProduction())
                    .as("check expectedProduction")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExpectedProduction())
            )
            .satisfies(a ->
                assertThat(a.getExpectedHarvestDate()).as("check expectedHarvestDate").isEqualTo(expected.getExpectedHarvestDate())
            )
            .satisfies(a -> assertThat(a.getActualHarvestDate()).as("check actualHarvestDate").isEqualTo(expected.getActualHarvestDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAquacultureProductionUpdatableRelationshipsEquals(
        AquacultureProduction expected,
        AquacultureProduction actual
    ) {
        assertThat(actual)
            .as("Verify AquacultureProduction relationships")
            .satisfies(a ->
                assertThat(a.getAquacultureActivity()).as("check aquacultureActivity").isEqualTo(expected.getAquacultureActivity())
            );
    }
}
