package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BranchUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchUserAllPropertiesEquals(BranchUser expected, BranchUser actual) {
        assertBranchUserAutoGeneratedPropertiesEquals(expected, actual);
        assertBranchUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchUserAllUpdatablePropertiesEquals(BranchUser expected, BranchUser actual) {
        assertBranchUserUpdatableFieldsEquals(expected, actual);
        assertBranchUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchUserAutoGeneratedPropertiesEquals(BranchUser expected, BranchUser actual) {
        assertThat(actual)
            .as("Verify BranchUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchUserUpdatableFieldsEquals(BranchUser expected, BranchUser actual) {
        assertThat(actual)
            .as("Verify BranchUser relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBranchUserUpdatableRelationshipsEquals(BranchUser expected, BranchUser actual) {
        assertThat(actual)
            .as("Verify BranchUser relationships")
            .satisfies(a -> assertThat(a.getAppUser()).as("check appUser").isEqualTo(expected.getAppUser()))
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }
}
