package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CooperativeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeAllPropertiesEquals(Cooperative expected, Cooperative actual) {
        assertCooperativeAutoGeneratedPropertiesEquals(expected, actual);
        assertCooperativeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeAllUpdatablePropertiesEquals(Cooperative expected, Cooperative actual) {
        assertCooperativeUpdatableFieldsEquals(expected, actual);
        assertCooperativeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeAutoGeneratedPropertiesEquals(Cooperative expected, Cooperative actual) {
        assertThat(actual)
            .as("Verify Cooperative auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeUpdatableFieldsEquals(Cooperative expected, Cooperative actual) {
        assertThat(actual)
            .as("Verify Cooperative relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLegalName()).as("check legalName").isEqualTo(expected.getLegalName()))
            .satisfies(a ->
                assertThat(a.getRegistrationNumber()).as("check registrationNumber").isEqualTo(expected.getRegistrationNumber())
            )
            .satisfies(a -> assertThat(a.getTaxNumber()).as("check taxNumber").isEqualTo(expected.getTaxNumber()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getFoundedDate()).as("check foundedDate").isEqualTo(expected.getFoundedDate()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getWebsite()).as("check website").isEqualTo(expected.getWebsite()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeUpdatableRelationshipsEquals(Cooperative expected, Cooperative actual) {
        // empty method
    }
}
