package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CooperativeRoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeRoleAllPropertiesEquals(CooperativeRole expected, CooperativeRole actual) {
        assertCooperativeRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertCooperativeRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeRoleAllUpdatablePropertiesEquals(CooperativeRole expected, CooperativeRole actual) {
        assertCooperativeRoleUpdatableFieldsEquals(expected, actual);
        assertCooperativeRoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeRoleAutoGeneratedPropertiesEquals(CooperativeRole expected, CooperativeRole actual) {
        assertThat(actual)
            .as("Verify CooperativeRole auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeRoleUpdatableFieldsEquals(CooperativeRole expected, CooperativeRole actual) {
        assertThat(actual)
            .as("Verify CooperativeRole relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeRoleUpdatableRelationshipsEquals(CooperativeRole expected, CooperativeRole actual) {
        assertThat(actual)
            .as("Verify CooperativeRole relationships")
            .satisfies(a -> assertThat(a.getPermissionses()).as("check permissionses").isEqualTo(expected.getPermissionses()));
    }
}
