package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CooperativeUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeUserAllPropertiesEquals(CooperativeUser expected, CooperativeUser actual) {
        assertCooperativeUserAutoGeneratedPropertiesEquals(expected, actual);
        assertCooperativeUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeUserAllUpdatablePropertiesEquals(CooperativeUser expected, CooperativeUser actual) {
        assertCooperativeUserUpdatableFieldsEquals(expected, actual);
        assertCooperativeUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeUserAutoGeneratedPropertiesEquals(CooperativeUser expected, CooperativeUser actual) {
        assertThat(actual)
            .as("Verify CooperativeUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeUserUpdatableFieldsEquals(CooperativeUser expected, CooperativeUser actual) {
        assertThat(actual)
            .as("Verify CooperativeUser relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeUserUpdatableRelationshipsEquals(CooperativeUser expected, CooperativeUser actual) {
        assertThat(actual)
            .as("Verify CooperativeUser relationships")
            .satisfies(a -> assertThat(a.getAppUser()).as("check appUser").isEqualTo(expected.getAppUser()))
            .satisfies(a -> assertThat(a.getCooperative()).as("check cooperative").isEqualTo(expected.getCooperative()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }
}
