package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CooperativeBranchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeBranchAllPropertiesEquals(CooperativeBranch expected, CooperativeBranch actual) {
        assertCooperativeBranchAutoGeneratedPropertiesEquals(expected, actual);
        assertCooperativeBranchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeBranchAllUpdatablePropertiesEquals(CooperativeBranch expected, CooperativeBranch actual) {
        assertCooperativeBranchUpdatableFieldsEquals(expected, actual);
        assertCooperativeBranchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeBranchAutoGeneratedPropertiesEquals(CooperativeBranch expected, CooperativeBranch actual) {
        assertThat(actual)
            .as("Verify CooperativeBranch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeBranchUpdatableFieldsEquals(CooperativeBranch expected, CooperativeBranch actual) {
        assertThat(actual)
            .as("Verify CooperativeBranch relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getOpeningDate()).as("check openingDate").isEqualTo(expected.getOpeningDate()))
            .satisfies(a -> assertThat(a.getClosingDate()).as("check closingDate").isEqualTo(expected.getClosingDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCooperativeBranchUpdatableRelationshipsEquals(CooperativeBranch expected, CooperativeBranch actual) {
        assertThat(actual)
            .as("Verify CooperativeBranch relationships")
            .satisfies(a -> assertThat(a.getCooperative()).as("check cooperative").isEqualTo(expected.getCooperative()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
