package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CropVarietyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyAllPropertiesEquals(CropVariety expected, CropVariety actual) {
        assertCropVarietyAutoGeneratedPropertiesEquals(expected, actual);
        assertCropVarietyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyAllUpdatablePropertiesEquals(CropVariety expected, CropVariety actual) {
        assertCropVarietyUpdatableFieldsEquals(expected, actual);
        assertCropVarietyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyAutoGeneratedPropertiesEquals(CropVariety expected, CropVariety actual) {
        assertThat(actual)
            .as("Verify CropVariety auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyUpdatableFieldsEquals(CropVariety expected, CropVariety actual) {
        assertThat(actual)
            .as("Verify CropVariety relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getOrigin()).as("check origin").isEqualTo(expected.getOrigin()))
            .satisfies(a -> assertThat(a.getMaturityDays()).as("check maturityDays").isEqualTo(expected.getMaturityDays()))
            .satisfies(a ->
                assertThat(a.getYieldPotential())
                    .as("check yieldPotential")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getYieldPotential())
            )
            .satisfies(a -> assertThat(a.getDiseaseResistance()).as("check diseaseResistance").isEqualTo(expected.getDiseaseResistance()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyUpdatableRelationshipsEquals(CropVariety expected, CropVariety actual) {
        assertThat(actual)
            .as("Verify CropVariety relationships")
            .satisfies(a -> assertThat(a.getCrop()).as("check crop").isEqualTo(expected.getCrop()));
    }
}
