package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CropAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropAllPropertiesEquals(Crop expected, Crop actual) {
        assertCropAutoGeneratedPropertiesEquals(expected, actual);
        assertCropAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropAllUpdatablePropertiesEquals(Crop expected, Crop actual) {
        assertCropUpdatableFieldsEquals(expected, actual);
        assertCropUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropAutoGeneratedPropertiesEquals(Crop expected, Crop actual) {
        assertThat(actual)
            .as("Verify Crop auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropUpdatableFieldsEquals(Crop expected, Crop actual) {
        assertThat(actual)
            .as("Verify Crop relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getScientificName()).as("check scientificName").isEqualTo(expected.getScientificName()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPerennial()).as("check perennial").isEqualTo(expected.getPerennial()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropUpdatableRelationshipsEquals(Crop expected, Crop actual) {
        // empty method
    }
}
