package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class EconomicActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityAllPropertiesEquals(EconomicActivity expected, EconomicActivity actual) {
        assertEconomicActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertEconomicActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityAllUpdatablePropertiesEquals(EconomicActivity expected, EconomicActivity actual) {
        assertEconomicActivityUpdatableFieldsEquals(expected, actual);
        assertEconomicActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityAutoGeneratedPropertiesEquals(EconomicActivity expected, EconomicActivity actual) {
        assertThat(actual)
            .as("Verify EconomicActivity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityUpdatableFieldsEquals(EconomicActivity expected, EconomicActivity actual) {
        assertThat(actual)
            .as("Verify EconomicActivity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMainActivity()).as("check mainActivity").isEqualTo(expected.getMainActivity()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a ->
                assertThat(a.getAnnualRevenue())
                    .as("check annualRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAnnualRevenue())
            )
            .satisfies(a ->
                assertThat(a.getMonthlyRevenue())
                    .as("check monthlyRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMonthlyRevenue())
            )
            .satisfies(a -> assertThat(a.getNumberOfEmployees()).as("check numberOfEmployees").isEqualTo(expected.getNumberOfEmployees()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityUpdatableRelationshipsEquals(EconomicActivity expected, EconomicActivity actual) {
        assertThat(actual)
            .as("Verify EconomicActivity relationships")
            .satisfies(a ->
                assertThat(a.getAgriculturalActivity()).as("check agriculturalActivity").isEqualTo(expected.getAgriculturalActivity())
            )
            .satisfies(a -> assertThat(a.getLivestockActivity()).as("check livestockActivity").isEqualTo(expected.getLivestockActivity()))
            .satisfies(a ->
                assertThat(a.getAquacultureActivity()).as("check aquacultureActivity").isEqualTo(expected.getAquacultureActivity())
            )
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()))
            .satisfies(a -> assertThat(a.getActivityType()).as("check activityType").isEqualTo(expected.getActivityType()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
