package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EconomicActivityTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityTypeAllPropertiesEquals(EconomicActivityType expected, EconomicActivityType actual) {
        assertEconomicActivityTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertEconomicActivityTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityTypeAllUpdatablePropertiesEquals(EconomicActivityType expected, EconomicActivityType actual) {
        assertEconomicActivityTypeUpdatableFieldsEquals(expected, actual);
        assertEconomicActivityTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityTypeAutoGeneratedPropertiesEquals(EconomicActivityType expected, EconomicActivityType actual) {
        assertThat(actual)
            .as("Verify EconomicActivityType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityTypeUpdatableFieldsEquals(EconomicActivityType expected, EconomicActivityType actual) {
        assertThat(actual)
            .as("Verify EconomicActivityType relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getSector()).as("check sector").isEqualTo(expected.getSector()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEconomicActivityTypeUpdatableRelationshipsEquals(EconomicActivityType expected, EconomicActivityType actual) {
        // empty method
    }
}
