package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyMemberAllPropertiesEquals(FamilyMember expected, FamilyMember actual) {
        assertFamilyMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyMemberAllUpdatablePropertiesEquals(FamilyMember expected, FamilyMember actual) {
        assertFamilyMemberUpdatableFieldsEquals(expected, actual);
        assertFamilyMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyMemberAutoGeneratedPropertiesEquals(FamilyMember expected, FamilyMember actual) {
        assertThat(actual)
            .as("Verify FamilyMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyMemberUpdatableFieldsEquals(FamilyMember expected, FamilyMember actual) {
        assertThat(actual)
            .as("Verify FamilyMember relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getMiddleName()).as("check middleName").isEqualTo(expected.getMiddleName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getRelationship()).as("check relationship").isEqualTo(expected.getRelationship()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()))
            .satisfies(a -> assertThat(a.getBirthPlace()).as("check birthPlace").isEqualTo(expected.getBirthPlace()))
            .satisfies(a -> assertThat(a.getNationality()).as("check nationality").isEqualTo(expected.getNationality()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getOccupation()).as("check occupation").isEqualTo(expected.getOccupation()))
            .satisfies(a -> assertThat(a.getDependent()).as("check dependent").isEqualTo(expected.getDependent()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyMemberUpdatableRelationshipsEquals(FamilyMember expected, FamilyMember actual) {
        assertThat(actual)
            .as("Verify FamilyMember relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()));
    }
}
