package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdentityDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentAllPropertiesEquals(IdentityDocument expected, IdentityDocument actual) {
        assertIdentityDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertIdentityDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentAllUpdatablePropertiesEquals(IdentityDocument expected, IdentityDocument actual) {
        assertIdentityDocumentUpdatableFieldsEquals(expected, actual);
        assertIdentityDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentAutoGeneratedPropertiesEquals(IdentityDocument expected, IdentityDocument actual) {
        assertThat(actual)
            .as("Verify IdentityDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentUpdatableFieldsEquals(IdentityDocument expected, IdentityDocument actual) {
        assertThat(actual)
            .as("Verify IdentityDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()))
            .satisfies(a -> assertThat(a.getDocumentNumber()).as("check documentNumber").isEqualTo(expected.getDocumentNumber()))
            .satisfies(a -> assertThat(a.getIssueDate()).as("check issueDate").isEqualTo(expected.getIssueDate()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getIssuingAuthority()).as("check issuingAuthority").isEqualTo(expected.getIssuingAuthority()))
            .satisfies(a -> assertThat(a.getIssuingCountry()).as("check issuingCountry").isEqualTo(expected.getIssuingCountry()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()))
            .satisfies(a -> assertThat(a.getVerificationDate()).as("check verificationDate").isEqualTo(expected.getVerificationDate()))
            .satisfies(a ->
                assertThat(a.getVerificationComment()).as("check verificationComment").isEqualTo(expected.getVerificationComment())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityDocumentUpdatableRelationshipsEquals(IdentityDocument expected, IdentityDocument actual) {
        assertThat(actual)
            .as("Verify IdentityDocument relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()));
    }
}
