package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IndividualMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndividualMemberAllPropertiesEquals(IndividualMember expected, IndividualMember actual) {
        assertIndividualMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertIndividualMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndividualMemberAllUpdatablePropertiesEquals(IndividualMember expected, IndividualMember actual) {
        assertIndividualMemberUpdatableFieldsEquals(expected, actual);
        assertIndividualMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndividualMemberAutoGeneratedPropertiesEquals(IndividualMember expected, IndividualMember actual) {
        assertThat(actual)
            .as("Verify IndividualMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndividualMemberUpdatableFieldsEquals(IndividualMember expected, IndividualMember actual) {
        assertThat(actual)
            .as("Verify IndividualMember relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getMiddleName()).as("check middleName").isEqualTo(expected.getMiddleName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getMaidenName()).as("check maidenName").isEqualTo(expected.getMaidenName()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()))
            .satisfies(a -> assertThat(a.getBirthPlace()).as("check birthPlace").isEqualTo(expected.getBirthPlace()))
            .satisfies(a -> assertThat(a.getNationality()).as("check nationality").isEqualTo(expected.getNationality()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getOccupation()).as("check occupation").isEqualTo(expected.getOccupation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndividualMemberUpdatableRelationshipsEquals(IndividualMember expected, IndividualMember actual) {
        // empty method
    }
}
