package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LivestockProductionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockProductionAllPropertiesEquals(LivestockProduction expected, LivestockProduction actual) {
        assertLivestockProductionAutoGeneratedPropertiesEquals(expected, actual);
        assertLivestockProductionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockProductionAllUpdatablePropertiesEquals(LivestockProduction expected, LivestockProduction actual) {
        assertLivestockProductionUpdatableFieldsEquals(expected, actual);
        assertLivestockProductionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockProductionAutoGeneratedPropertiesEquals(LivestockProduction expected, LivestockProduction actual) {
        assertThat(actual)
            .as("Verify LivestockProduction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockProductionUpdatableFieldsEquals(LivestockProduction expected, LivestockProduction actual) {
        assertThat(actual)
            .as("Verify LivestockProduction relevant properties")
            .satisfies(a -> assertThat(a.getProductionDate()).as("check productionDate").isEqualTo(expected.getProductionDate()))
            .satisfies(a -> assertThat(a.getAnimalSex()).as("check animalSex").isEqualTo(expected.getAnimalSex()))
            .satisfies(a -> assertThat(a.getNumberOfAnimals()).as("check numberOfAnimals").isEqualTo(expected.getNumberOfAnimals()))
            .satisfies(a -> assertThat(a.getAverageAgeMonths()).as("check averageAgeMonths").isEqualTo(expected.getAverageAgeMonths()))
            .satisfies(a ->
                assertThat(a.getAverageWeightKg())
                    .as("check averageWeightKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAverageWeightKg())
            )
            .satisfies(a ->
                assertThat(a.getProductionQuantity())
                    .as("check productionQuantity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getProductionQuantity())
            )
            .satisfies(a -> assertThat(a.getProductionUnit()).as("check productionUnit").isEqualTo(expected.getProductionUnit()))
            .satisfies(a -> assertThat(a.getMortalityCount()).as("check mortalityCount").isEqualTo(expected.getMortalityCount()))
            .satisfies(a -> assertThat(a.getBirthCount()).as("check birthCount").isEqualTo(expected.getBirthCount()))
            .satisfies(a -> assertThat(a.getSoldCount()).as("check soldCount").isEqualTo(expected.getSoldCount()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockProductionUpdatableRelationshipsEquals(LivestockProduction expected, LivestockProduction actual) {
        assertThat(actual)
            .as("Verify LivestockProduction relationships")
            .satisfies(a -> assertThat(a.getLivestockActivity()).as("check livestockActivity").isEqualTo(expected.getLivestockActivity()));
    }
}
