package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LivestockActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockActivityAllPropertiesEquals(LivestockActivity expected, LivestockActivity actual) {
        assertLivestockActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertLivestockActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockActivityAllUpdatablePropertiesEquals(LivestockActivity expected, LivestockActivity actual) {
        assertLivestockActivityUpdatableFieldsEquals(expected, actual);
        assertLivestockActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockActivityAutoGeneratedPropertiesEquals(LivestockActivity expected, LivestockActivity actual) {
        assertThat(actual)
            .as("Verify LivestockActivity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockActivityUpdatableFieldsEquals(LivestockActivity expected, LivestockActivity actual) {
        assertThat(actual)
            .as("Verify LivestockActivity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getProductionMode()).as("check productionMode").isEqualTo(expected.getProductionMode()))
            .satisfies(a -> assertThat(a.getOwnershipType()).as("check ownershipType").isEqualTo(expected.getOwnershipType()))
            .satisfies(a -> assertThat(a.getProductionType()).as("check productionType").isEqualTo(expected.getProductionType()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a ->
                assertThat(a.getTotalArea()).as("check totalArea").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalArea())
            )
            .satisfies(a -> assertThat(a.getAreaUnit()).as("check areaUnit").isEqualTo(expected.getAreaUnit()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNumberOfAnimals()).as("check numberOfAnimals").isEqualTo(expected.getNumberOfAnimals()))
            .satisfies(a ->
                assertThat(a.getAnnualRevenue())
                    .as("check annualRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAnnualRevenue())
            )
            .satisfies(a ->
                assertThat(a.getMonthlyRevenue())
                    .as("check monthlyRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMonthlyRevenue())
            )
            .satisfies(a -> assertThat(a.getEmployees()).as("check employees").isEqualTo(expected.getEmployees()))
            .satisfies(a ->
                assertThat(a.getVeterinaryServiceAvailable())
                    .as("check veterinaryServiceAvailable")
                    .isEqualTo(expected.getVeterinaryServiceAvailable())
            )
            .satisfies(a -> assertThat(a.getFeedSource()).as("check feedSource").isEqualTo(expected.getFeedSource()))
            .satisfies(a -> assertThat(a.getWaterSource()).as("check waterSource").isEqualTo(expected.getWaterSource()))
            .satisfies(a -> assertThat(a.getCertification()).as("check certification").isEqualTo(expected.getCertification()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockActivityUpdatableRelationshipsEquals(LivestockActivity expected, LivestockActivity actual) {
        assertThat(actual)
            .as("Verify LivestockActivity relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getLivestockType()).as("check livestockType").isEqualTo(expected.getLivestockType()));
    }
}
