package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LivestockTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockTypeAllPropertiesEquals(LivestockType expected, LivestockType actual) {
        assertLivestockTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertLivestockTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockTypeAllUpdatablePropertiesEquals(LivestockType expected, LivestockType actual) {
        assertLivestockTypeUpdatableFieldsEquals(expected, actual);
        assertLivestockTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockTypeAutoGeneratedPropertiesEquals(LivestockType expected, LivestockType actual) {
        assertThat(actual)
            .as("Verify LivestockType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockTypeUpdatableFieldsEquals(LivestockType expected, LivestockType actual) {
        assertThat(actual)
            .as("Verify LivestockType relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getScientificName()).as("check scientificName").isEqualTo(expected.getScientificName()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLivestockTypeUpdatableRelationshipsEquals(LivestockType expected, LivestockType actual) {
        // empty method
    }
}
