package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MembershipApplicationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipApplicationAllPropertiesEquals(MembershipApplication expected, MembershipApplication actual) {
        assertMembershipApplicationAutoGeneratedPropertiesEquals(expected, actual);
        assertMembershipApplicationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipApplicationAllUpdatablePropertiesEquals(
        MembershipApplication expected,
        MembershipApplication actual
    ) {
        assertMembershipApplicationUpdatableFieldsEquals(expected, actual);
        assertMembershipApplicationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipApplicationAutoGeneratedPropertiesEquals(
        MembershipApplication expected,
        MembershipApplication actual
    ) {
        assertThat(actual)
            .as("Verify MembershipApplication auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipApplicationUpdatableFieldsEquals(MembershipApplication expected, MembershipApplication actual) {
        assertThat(actual)
            .as("Verify MembershipApplication relevant properties")
            .satisfies(a -> assertThat(a.getApplicationNumber()).as("check applicationNumber").isEqualTo(expected.getApplicationNumber()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getApplicationDate()).as("check applicationDate").isEqualTo(expected.getApplicationDate()))
            .satisfies(a -> assertThat(a.getSubmittedAt()).as("check submittedAt").isEqualTo(expected.getSubmittedAt()))
            .satisfies(a -> assertThat(a.getReviewedAt()).as("check reviewedAt").isEqualTo(expected.getReviewedAt()))
            .satisfies(a -> assertThat(a.getApprovedAt()).as("check approvedAt").isEqualTo(expected.getApprovedAt()))
            .satisfies(a -> assertThat(a.getRejectedAt()).as("check rejectedAt").isEqualTo(expected.getRejectedAt()))
            .satisfies(a -> assertThat(a.getRejectionReason()).as("check rejectionReason").isEqualTo(expected.getRejectionReason()))
            .satisfies(a -> assertThat(a.getReviewComments()).as("check reviewComments").isEqualTo(expected.getReviewComments()))
            .satisfies(a -> assertThat(a.getConfirmation()).as("check confirmation").isEqualTo(expected.getConfirmation()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipApplicationUpdatableRelationshipsEquals(
        MembershipApplication expected,
        MembershipApplication actual
    ) {
        assertThat(actual)
            .as("Verify MembershipApplication relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()))
            .satisfies(a -> assertThat(a.getCooperative()).as("check cooperative").isEqualTo(expected.getCooperative()))
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()));
    }
}
