package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberAllPropertiesEquals(Member expected, Member actual) {
        assertMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberAllUpdatablePropertiesEquals(Member expected, Member actual) {
        assertMemberUpdatableFieldsEquals(expected, actual);
        assertMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberAutoGeneratedPropertiesEquals(Member expected, Member actual) {
        assertThat(actual)
            .as("Verify Member auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberUpdatableFieldsEquals(Member expected, Member actual) {
        assertThat(actual)
            .as("Verify Member relevant properties")
            .satisfies(a -> assertThat(a.getMemberNumber()).as("check memberNumber").isEqualTo(expected.getMemberNumber()))
            .satisfies(a -> assertThat(a.getMemberType()).as("check memberType").isEqualTo(expected.getMemberType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAdmissionDate()).as("check admissionDate").isEqualTo(expected.getAdmissionDate()))
            .satisfies(a -> assertThat(a.getExitDate()).as("check exitDate").isEqualTo(expected.getExitDate()))
            .satisfies(a -> assertThat(a.getExitReason()).as("check exitReason").isEqualTo(expected.getExitReason()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberUpdatableRelationshipsEquals(Member expected, Member actual) {
        assertThat(actual)
            .as("Verify Member relationships")
            .satisfies(a -> assertThat(a.getIndividualMember()).as("check individualMember").isEqualTo(expected.getIndividualMember()))
            .satisfies(a ->
                assertThat(a.getOrganizationMember()).as("check organizationMember").isEqualTo(expected.getOrganizationMember())
            )
            .satisfies(a -> assertThat(a.getSocialProfile()).as("check socialProfile").isEqualTo(expected.getSocialProfile()))
            .satisfies(a ->
                assertThat(a.getProfessionalProfile()).as("check professionalProfile").isEqualTo(expected.getProfessionalProfile())
            )
            .satisfies(a -> assertThat(a.getCooperative()).as("check cooperative").isEqualTo(expected.getCooperative()))
            .satisfies(a -> assertThat(a.getBranch()).as("check branch").isEqualTo(expected.getBranch()));
    }
}
