package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MemberDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberDocumentAllPropertiesEquals(MemberDocument expected, MemberDocument actual) {
        assertMemberDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertMemberDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberDocumentAllUpdatablePropertiesEquals(MemberDocument expected, MemberDocument actual) {
        assertMemberDocumentUpdatableFieldsEquals(expected, actual);
        assertMemberDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberDocumentAutoGeneratedPropertiesEquals(MemberDocument expected, MemberDocument actual) {
        assertThat(actual)
            .as("Verify MemberDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberDocumentUpdatableFieldsEquals(MemberDocument expected, MemberDocument actual) {
        assertThat(actual)
            .as("Verify MemberDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()))
            .satisfies(a -> assertThat(a.getOriginalFileName()).as("check originalFileName").isEqualTo(expected.getOriginalFileName()))
            .satisfies(a -> assertThat(a.getStoredFileName()).as("check storedFileName").isEqualTo(expected.getStoredFileName()))
            .satisfies(a -> assertThat(a.getContentType()).as("check contentType").isEqualTo(expected.getContentType()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getStoragePath()).as("check storagePath").isEqualTo(expected.getStoragePath()))
            .satisfies(a -> assertThat(a.getChecksum()).as("check checksum").isEqualTo(expected.getChecksum()))
            .satisfies(a ->
                assertThat(a.getVerificationStatus()).as("check verificationStatus").isEqualTo(expected.getVerificationStatus())
            )
            .satisfies(a -> assertThat(a.getUploadedAt()).as("check uploadedAt").isEqualTo(expected.getUploadedAt()))
            .satisfies(a -> assertThat(a.getVerifiedAt()).as("check verifiedAt").isEqualTo(expected.getVerifiedAt()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMemberDocumentUpdatableRelationshipsEquals(MemberDocument expected, MemberDocument actual) {
        assertThat(actual)
            .as("Verify MemberDocument relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()))
            .satisfies(a -> assertThat(a.getUploadedBy()).as("check uploadedBy").isEqualTo(expected.getUploadedBy()));
    }
}
