package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NumberSequenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumberSequenceAllPropertiesEquals(NumberSequence expected, NumberSequence actual) {
        assertNumberSequenceAutoGeneratedPropertiesEquals(expected, actual);
        assertNumberSequenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumberSequenceAllUpdatablePropertiesEquals(NumberSequence expected, NumberSequence actual) {
        assertNumberSequenceUpdatableFieldsEquals(expected, actual);
        assertNumberSequenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumberSequenceAutoGeneratedPropertiesEquals(NumberSequence expected, NumberSequence actual) {
        assertThat(actual)
            .as("Verify NumberSequence auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumberSequenceUpdatableFieldsEquals(NumberSequence expected, NumberSequence actual) {
        assertThat(actual)
            .as("Verify NumberSequence relevant properties")
            .satisfies(a -> assertThat(a.getSequenceType()).as("check sequenceType").isEqualTo(expected.getSequenceType()))
            .satisfies(a -> assertThat(a.getPrefix()).as("check prefix").isEqualTo(expected.getPrefix()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getCurrentValue()).as("check currentValue").isEqualTo(expected.getCurrentValue()))
            .satisfies(a -> assertThat(a.getPadding()).as("check padding").isEqualTo(expected.getPadding()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNumberSequenceUpdatableRelationshipsEquals(NumberSequence expected, NumberSequence actual) {
        assertThat(actual)
            .as("Verify NumberSequence relationships")
            .satisfies(a -> assertThat(a.getCooperative()).as("check cooperative").isEqualTo(expected.getCooperative()));
    }
}
