package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganizationMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMemberAllPropertiesEquals(OrganizationMember expected, OrganizationMember actual) {
        assertOrganizationMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganizationMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMemberAllUpdatablePropertiesEquals(OrganizationMember expected, OrganizationMember actual) {
        assertOrganizationMemberUpdatableFieldsEquals(expected, actual);
        assertOrganizationMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMemberAutoGeneratedPropertiesEquals(OrganizationMember expected, OrganizationMember actual) {
        assertThat(actual)
            .as("Verify OrganizationMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMemberUpdatableFieldsEquals(OrganizationMember expected, OrganizationMember actual) {
        assertThat(actual)
            .as("Verify OrganizationMember relevant properties")
            .satisfies(a -> assertThat(a.getLegalName()).as("check legalName").isEqualTo(expected.getLegalName()))
            .satisfies(a -> assertThat(a.getTradeName()).as("check tradeName").isEqualTo(expected.getTradeName()))
            .satisfies(a ->
                assertThat(a.getRegistrationNumber()).as("check registrationNumber").isEqualTo(expected.getRegistrationNumber())
            )
            .satisfies(a -> assertThat(a.getTaxNumber()).as("check taxNumber").isEqualTo(expected.getTaxNumber()))
            .satisfies(a -> assertThat(a.getLegalForm()).as("check legalForm").isEqualTo(expected.getLegalForm()))
            .satisfies(a -> assertThat(a.getRegistrationDate()).as("check registrationDate").isEqualTo(expected.getRegistrationDate()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getWebsite()).as("check website").isEqualTo(expected.getWebsite()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMemberUpdatableRelationshipsEquals(OrganizationMember expected, OrganizationMember actual) {
        // empty method
    }
}
