package com.naline.coopfull.domain;

import static com.naline.coopfull.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalProfileAllPropertiesEquals(ProfessionalProfile expected, ProfessionalProfile actual) {
        assertProfessionalProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalProfileAllUpdatablePropertiesEquals(ProfessionalProfile expected, ProfessionalProfile actual) {
        assertProfessionalProfileUpdatableFieldsEquals(expected, actual);
        assertProfessionalProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalProfileAutoGeneratedPropertiesEquals(ProfessionalProfile expected, ProfessionalProfile actual) {
        assertThat(actual)
            .as("Verify ProfessionalProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalProfileUpdatableFieldsEquals(ProfessionalProfile expected, ProfessionalProfile actual) {
        assertThat(actual)
            .as("Verify ProfessionalProfile relevant properties")
            .satisfies(a -> assertThat(a.getEmploymentStatus()).as("check employmentStatus").isEqualTo(expected.getEmploymentStatus()))
            .satisfies(a -> assertThat(a.getEmployerName()).as("check employerName").isEqualTo(expected.getEmployerName()))
            .satisfies(a -> assertThat(a.getJobTitle()).as("check jobTitle").isEqualTo(expected.getJobTitle()))
            .satisfies(a -> assertThat(a.getProfession()).as("check profession").isEqualTo(expected.getProfession()))
            .satisfies(a -> assertThat(a.getSector()).as("check sector").isEqualTo(expected.getSector()))
            .satisfies(a -> assertThat(a.getYearsOfExperience()).as("check yearsOfExperience").isEqualTo(expected.getYearsOfExperience()))
            .satisfies(a ->
                assertThat(a.getMonthlyIncome())
                    .as("check monthlyIncome")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMonthlyIncome())
            )
            .satisfies(a ->
                assertThat(a.getAnnualIncome())
                    .as("check annualIncome")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAnnualIncome())
            )
            .satisfies(a ->
                assertThat(a.getEmploymentStartDate()).as("check employmentStartDate").isEqualTo(expected.getEmploymentStartDate())
            )
            .satisfies(a -> assertThat(a.getEmployerLocation()).as("check employerLocation").isEqualTo(expected.getEmployerLocation()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalProfileUpdatableRelationshipsEquals(ProfessionalProfile expected, ProfessionalProfile actual) {
        // empty method
    }
}
