package com.naline.coopfull.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SocialProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialProfileAllPropertiesEquals(SocialProfile expected, SocialProfile actual) {
        assertSocialProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertSocialProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialProfileAllUpdatablePropertiesEquals(SocialProfile expected, SocialProfile actual) {
        assertSocialProfileUpdatableFieldsEquals(expected, actual);
        assertSocialProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialProfileAutoGeneratedPropertiesEquals(SocialProfile expected, SocialProfile actual) {
        assertThat(actual)
            .as("Verify SocialProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialProfileUpdatableFieldsEquals(SocialProfile expected, SocialProfile actual) {
        assertThat(actual)
            .as("Verify SocialProfile relevant properties")
            .satisfies(a -> assertThat(a.getMaritalStatus()).as("check maritalStatus").isEqualTo(expected.getMaritalStatus()))
            .satisfies(a -> assertThat(a.getNumberOfChildren()).as("check numberOfChildren").isEqualTo(expected.getNumberOfChildren()))
            .satisfies(a ->
                assertThat(a.getNumberOfDependents()).as("check numberOfDependents").isEqualTo(expected.getNumberOfDependents())
            )
            .satisfies(a -> assertThat(a.getEducationLevel()).as("check educationLevel").isEqualTo(expected.getEducationLevel()))
            .satisfies(a -> assertThat(a.getHousingStatus()).as("check housingStatus").isEqualTo(expected.getHousingStatus()))
            .satisfies(a -> assertThat(a.getResidenceSince()).as("check residenceSince").isEqualTo(expected.getResidenceSince()))
            .satisfies(a -> assertThat(a.getDisabilityStatus()).as("check disabilityStatus").isEqualTo(expected.getDisabilityStatus()))
            .satisfies(a ->
                assertThat(a.getDisabilityDescription()).as("check disabilityDescription").isEqualTo(expected.getDisabilityDescription())
            )
            .satisfies(a -> assertThat(a.getSocialCategory()).as("check socialCategory").isEqualTo(expected.getSocialCategory()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocialProfileUpdatableRelationshipsEquals(SocialProfile expected, SocialProfile actual) {
        // empty method
    }
}
